branches:
    only:
        - gh-pages
before_script:
    - npm i -g javascript-obfuscator
jobs:
    include:
        - stage: obfusscate
          script:
            - javascript-obfuscator game/planez.js --output game/obfussed.js --compact true
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    repo: obfusscated
    on:
        branch: gh-pages
cache: npm
